### ISSUE TITLE
Renderer aemgpt/components/page is missing in the code repository. 

### ISSUE THREAD

**Issue by shivakumar660** [jaketracey/opax#4]
I have followed all the steps, after installing the package, when I try to hit http://localhost:4502/content/aemgpt/us/en.html
I get the following error message. I noticed that /apps/aemgpt has only clientlibs and osgiconfig, where are the components ? 
where is the rendered for "aemgpt/components/page" defined ? 

02.07.2023 22:14:31.624 *ERROR* [[0:0:0:0:0:0:0:1] [1688316271613] GET /content/aemgpt/us/en.html HTTP/1.1] org.apache.sling.servlets.get.impl.DefaultGetServlet No renderer for extension html, cannot render resource JcrNodeResource, type=aemgpt/components/page, superType=null, path=/content/aemgpt/us/en/jcr:content

**Comment by jaketracey** [comment]
Hi @shivakumar660 

Should work now. As the project doesn't need the archetype components I removed them. Will add some additional examples in future!

Let me know if that works for you.

- Jake

**Comment by shivakumar660** [comment]
Hi Jake,
Thank you for the quick response. 
I see that in the filter.xml of ui.apps, you have added the path till clientlibs "//apps/aemgpt/clientlibs" , so its not picking the components as part of deployment. ct?  I would like to contribute for bug fixes or new features development. 
I have around 10 years of experience as a AEM Developer , here is my linkedIn - https://www.linkedin.com/in/shivakumar-chandrappa-3221642a/

**Comment by jaketracey** [comment]
Hi Shivakumar,

Feel free to make a PR! Happy to have any contributions.

The integration itself does not need any components added, so unless for examples there really isn't a need for any to be included in this package.

The author clientlib attaches to the components on this line:
https://github.com/jaketracey/opax/blob/7a7c50d5fc78b8c957b763272610979bda0ab80b/ui.frontend/src/main/webpack/site/main.js#L22C27-L22C40

Ultimately we want to modify this so that it uses the OSGI configuration so that it's configurable which component the integration attaches to (not just wcm/text/v2 as it currently is.

**Comment by shivakumar660** [comment]
<img width="1342" alt="image" src="https://github.com/jaketracey/opax/assets/5644750/8660a5c0-01a0-4a42-8715-4c4433a4f914">

I am getting this message when I try to raise a PR 
"Pull request creation failed. Validation failed: must be a collaborator"

**Comment by jaketracey** [comment]
Fixed - should work now!

**Comment by shivakumar660** [comment]
https://github.com/jaketracey/opax/pull/7
I have created a PR.

**Comment by shivakumar660** [comment]
PR is merged. Hence closing this issue.
